### ISSUE TITLE
Missing JWT token

### ISSUE THREAD

**Issue by sblack4** [vouch/helm-charts#28]
I'm trying to upgrade from version `1.0.0` and it's giving me an error. I think all it needs is a random string to be the secret but for unenlightened like me, this takes some googling to figure out that would be great to include in some docs :) 

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/15880760/175358851-449781ec-b3d0-4b4f-a1c3-aa04c01ab1a5.png">

**Comment by punkle** [comment]
I think if this setting is unset then the vouch application will default to a randomly generated secret on each boot. If that is correct it might be sensible to default to unset and allow it to be set optionally.

@bnfinet am I correct about the secret being randomly generated? If so do you think it's sensible to allow the secret be unset by the helm chart?

**Comment by bnfinet** [comment]
@punkle yes that's right

If `vouch.jwt.secret` is not configured...
https://github.com/vouch/vouch-proxy/blob/master/pkg/cfg/cfg.go#L343

otherwise we try to read it from the file `$ROOTDIR/config/secret`.  If that file does not exist then the secret is generated randomly and stored in that file and sets `vouch.jwt.secret` for this run and any subsequent runs. 
https://github.com/vouch/vouch-proxy/blob/master/pkg/cfg/jwt.go
